export const ROLES = {
  ADMIN: 'ADMIN',
  DOCTOR: 'DOCTOR',
  RECEPTIONIST: 'RECEPTIONIST',
  LAB: 'LAB',
};

export const VISIT_STATUS = {
  SENT_TO_CASHIER: 'SENT_TO_CASHIER',
  PENDING_DOCTOR: 'PENDING_DOCTOR',
  LAB_REQUESTED: 'LAB_REQUESTED',
  LAB_COMPLETED: 'LAB_COMPLETED',
  COMPLETED: 'COMPLETED',
};

export const PAYMENT_STATUS = {
  UNPAID: 'UNPAID',
  PAID: 'PAID',
};

export const APPOINTMENT_STATUS = {
  SCHEDULED: 'SCHEDULED',
  CHECKED_IN: 'CHECKED_IN',
  CANCELLED: 'CANCELLED',
};

export const LAB_ORDER_STATUS = {
  PENDING: 'PENDING',
  IN_PROGRESS: 'IN_PROGRESS',
  COMPLETED: 'COMPLETED',
};

export const LAB_PRIORITY = {
  NORMAL: 'NORMAL',
  URGENT: 'URGENT',
};
